streamcommerce:
  outputs:
    dev:
      dataset: staging_streamcommerce
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: black-machine-422712-b7
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: prod_streamcommerce
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: black-machine-422712-b7
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev